name: Run compose
on: [ push ]

jobs:
  run-compose:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Start docker compose
        run: docker compose version
