name: Run compose
on: [push]

jobs:
  run-comose:
    timeout-minutes: 10
    runs-on: ubuntu-latest
  
  steps:
  - name: Checkout
    users: actions/checkout@main
  - name: Start docker compose
    run: docker compose version
